---
title: "Lit Review"
author: "Lara Volski"
date: "2022-08-05"
output: html_document
---


Included Studies
```{r}
# note, I subtracted 4 papers from the lit review/tool eval and 2 papeers from the e study/con desc pulled them into gray lit. This is not reflected in the google sheets.

# old slides from the first draft slices <- c(7, 4, 23, 10, 17)

Review.ConDesc <- 7 + 2
Review.ToolEval <- 7
Estudy.ConDesc <- 27
Estudy.ToolEval <- 8 + 3
Estudy.Socialactors <- 13
GrayLit <- 14

slices <- c(Review.ConDesc, Review.ToolEval, Estudy.ConDesc, Estudy.ToolEval, Estudy.Socialactors, GrayLit)
lbls <- c("Review/Conflict Description", "Review/Tool Evaluation", "Empirical Study/Conflict Description", "Empirical Study/Tool", "Social Attitudes", "Gray Literature")
pie(slices, labels = lbls, main="Included Papers", col=c("steelblue2", "steelblue", "darkolivegreen3", "darkolivegreen4", "#FFA500", "darkgrey"))
```
Cattle
```{r}
## Bobcats do not predate cattle
slices <- c(2, 1)
lbls <- c("Rancher Survey", "Camera Trap Observations")
pie(slices, col=c("#53868B", "#FFA500"))
```
Sheep/Goat
```{r}
## Bobcats predate sheep/goats

# Young 1958 - stomach content analysis
# Gashwiler et al. 1960 - stomach content analysis
# Kaiser 1975 - fed/state/county reporting
# Klebenow and McAdoo 1975 - empirical study
# Fritts and Sealander 1978 - stomach content analysis
# Pearson and Caroline 1981 - fed/state/county reporting
# Green 1983 - emprical study
# Howard 1985 - rancher survey
# Goodwin 1985 -fed/state/county reporting
# NASS 1991 - fed/state/county reporting
# NASS 1995 - fed/state/county reporting
# USDA 1997 - fed/state/county reporting
# Altman 1997 - stomach content analysis
# NASS 2000 -fed/state/county reporting
# NASS 2005 - fed/state/county reporting
# Scasta et al. 2017 - rncher survey
# USDA 2017 - fed/state/county reporting
# Holland-Levine 2020 - fed/state/county reporting
# Floyd 2022 - empirical study
# Wildlife Services 1996 - 2021 - fed/state/county reporting

slices <- c(11, 7, 2)
pie(slices, col=c("#749665", "#53868B", "#FFA500"))

## Bobcats do not predate sheep/goats
slices <- c(2, 1, 1)
pie(slices, col=c("#53868B", "#749665", "#FFA500"))
```

Poultry
```{r}
## Bobcats predate poultry
# Gashwiler et al. 1960 - stomach content analysis
# Fritts and Sealander 1978 - stomach content analysis
# Miller 1980 - stomach content analysis
# Pearson and Caroline 1981 - fed/state/county reporting
# Knick et al. 1984 - stomach content analysis
# Maehr 1989 - stomach content analysis
# Fox 1990 - stomach content analysis
# Arroyo-Quiroz 2017 - Producer survey
# USDA 2017 - fed/state/county reporting
# Fergus 2020 - field research
# Wildlife Services 1996 – 2021 - fed/state/county reporting

slices <- c(7, 3, 1)
pie(slices, col=c("#53868B", "#749665", "#FFA500"))

## Bobcats do not predate poultry
slices <- c(1)
pie(slices, col=c("steelblue2"))
```


Land Types in Studies
```{r}
slices <- c(12, 5, 2, 5, 9)
pie(slices, col=c("#53868B", "#FFA500", "#749665", "darkslategray3", "rosybrown1"))


slices <- c(5, 0, 8)
pie(slices, col=c("steelblue3", "steelblue3", "#53868B"))
```
Attitudes
```{r}
slices <- c(5, 1, 1, 1)
pie(slices, col=c("#53868B", "#FFA500", "#749665", "darkslategray3"))

```

Wildlife Services
```{r}
slices <- c(857,	16671,	23581,	2689)
lbls <- c("Cattle", "Sheep/Goats", "Domestic Fowl", "Pets")
pie(slices, labels = lbls, main="Damage or Threats Addressed by Wildlife Services 1996 - 2021", col=c("#749665", "#53868B", "#FFA500", "darkgrey"))
```

